config/routes.rb
Unchartedleague::Application.routes.draw do  
  opinio_model

  root :to => 'home#index'  
  devise_for :users  
  match 'matches/:id/check_results' => 'matches#check_results', :via => :get
  match 'matches/:id/commit_results' => 'matches#commit_results', :via => :post
  match 'stats/:competition_id/ranking' => 'stats#ranking', :via => :get, :as => :stats_ranking
  match 'stats/:competition_id/players' => 'stats#players', :via => :get, :as => :stats_players

  resources :teams
  resources :team_participations
  resources :offers
  resources :competitions
  resources :competition_entries
  resources :matches do
    opinio
  end
  resources :match_maps
  resources :maps
  resources :match_map_images
  resources :match_time_proposals
  resources :rounds
  resources :awards
  resources :articles
  resources :users
  

end

app/models/competition.rb
class Competition < ActiveRecord::Base
  belongs_to :parent_competition, :class_name => "Competition"
  has_many :teams, :through => :competition_entries
  has_many :competition_entries, :dependent => :destroy  
  has_many :competition_judges, :dependent => :destroy
  has_many :competition_maps, :dependent => :destroy
  has_many :competition_optional_maps, :dependent => :destroy
  has_many :rounds
  has_many :matches
  
  validates :name, :presence => true
  
  accepts_nested_attributes_for :competition_entries, :allow_destroy => true
  accepts_nested_attributes_for :competition_judges, :allow_destroy => true
  accepts_nested_attributes_for :competition_maps, :allow_destroy => true
  accepts_nested_attributes_for :competition_optional_maps, :allow_destroy => true
  
  def root
    c = self
    while c.parent_competition != nil
      c = c.parent_competition
    end
    c
  end
  
  def all_competitions
    Competition.where('parent_competition_id = ? or id = ?', id, id).order("id asc")
  end
  
  # team
  def min_players
    6 # FIXME WTF? 
  end
  
  # match
  def min_players_per_team
    4 # WTF>!>?!
  end
  
  def max_players_per_team
    5 # you gotta be kiddin me :/
  end
  
  def is_user_signed_up? (user)
    user_teams = Team.joins(:team_participations, :competition_entries).where("team_participations.user_id = ? and team_participations.active = ? and competition_id = ?", user.id, true, id)
    return !user_teams.empty?
  end
  
  def can_team_be_signed_up? (team)
    team.users.size >= min_players
  end
  
  def can_user_leave_team? (team)
    ends < DateTime.current or team.users.size > min_players
  end
  
  def get_judge
    judged_matches = {}
    for j in competition_judges
      judged_matches[j.user] = 0
    end
    
    for m in matches
      if  m.judge.present? and judged_matches.key? m.judge
        judged_matches[m.judge] += 1
      end
    end
    
    best = nil
    judged_matches.each do |judge, qty|
      if best.nil? or qty < judged_matches[best]
        best = judge
      end
    end
    
    return best
  end
  
  def to_s
    name
  end
  
  def long_name
    if parent_competition != nil
      "#{name} - #{parent_competition.long_name}"
    else
      "#{name} (sezon #{season})" # FIXME: it should not be hardcoded, damn!
    end
  end
  
  def stats_config
    result = { 
      :additional_matches_ids => [],
      :seeded_teams => {},
      :remove_forfeited => false,
      :show_place => true,
      :starting_place => 1,
      :starting_points => {},
      :reject_conditions => ["x.matches == 0"],
      :sorting_condition => "[-x.points, -x.frags_diff, -x.frags_for]",
      :fields => "['matches', 'points', 'maps', 'wins', 'losses', 'not_played', 'frags_for', 'frags_against', 'frags_diff']",      
      :additional_fields => {}
    }
    if team_stats_config.present?
      result.merge!(eval(team_stats_config))
    end
    return result
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  load_and_authorize_resource

  def index
    @competitions = Competition.where("parent_competition_id is ?", nil).order("ends desc")
  end
  
  def show
    @competition = Competition.find(params[:id])
    @subcompetitions = Competition.where('parent_competition_id = ?', @competition.id)
    if user_signed_in? and @competition.signup_ends > DateTime.current
      @signed_up_teams_ids = @competition.competition_entries.collect { |x| x.team.id }
      @possible_teams = Team.joins(:team_participations).where("team_participations.user_id = ? and team_participations.role = ?", current_user.id, 0)
      @possible_teams = @possible_teams.select { |x| not @signed_up_teams_ids.include? x.id }
    end
  end

  def new
    @competition = Competition.new
  end

  def edit
    @competition = Competition.find(params[:id])
  end

  def create
    @competition = Competition.new(params[:competition])
    if @competition.save
      flash[:success] = @competition.name + " created"
      redirect_to @competition
    else
      flash[:error] = "Problem while saving"
      render 'new'
    end
  end

  def update
    @competition = Competition.find(params[:id])
    if @competition.update_attributes(params[:competition])
      flash[:success] = @competition.name + " updated"
      redirect_to @competition
    else
      flash[:error] = "Problem while saving changes"
      render @competition
    end
  end

  def destroy
    @competition = Competition.find(params[:id])
    if @competition.destroy
      flash[:success] = @competition.name + " destroyed!"
      redirect_to new_competition_path
    else
      flash[:error] = "Problem while destroying"
      render 'new'
    end
  end
end

app/views/competitions/_competition_entry_fields.html.erb
<p class="fields">
  <%= f.select(:team_id, Team.all.collect { |x| [x, x.id] }) %>
  <%= f.hidden_field :_destroy %>
  <%= link_to_function "remove", "remove_fields(this)" %>
</p>

app/views/competitions/_competition_judge_fields.html.erb
<p class="fields">
  <%= f.select(:user_id, User.order("LOWER(psn_name) asc").collect { |x| [x, x.id] }) %>
  <%= f.hidden_field :_destroy %>
  <%= link_to_function "remove", "remove_fields(this)" %>
</p>

app/views/competitions/_competition_map_fields.html.erb
<p class="fields">
  <%= f.select(:map_id, Map.order("LOWER(name) asc").collect { |x| [x, x.id] }) %>
  <%= f.hidden_field :_destroy %>
  <%= link_to_function "remove", "remove_fields(this)" %>
</p>

app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p><%= f.label :name %> <%= f.text_field :name %></p>
  <p><%= f.label :status %> <%= f.text_field :status %></p>
  <p><%= f.label :season %> <%= f.text_field :season %></p>
  <p><%= f.label :parent_competition %> <%= f.select(:parent_competition_id, Competition.where("parent_competition_id is ?", nil).collect {|x| [x.name, x.id]}, { :include_blank => "" } ) %></p>
  <p><%= f.label :starts %> <%= datetime_select("competition", "starts") %></p>
  <p><%= f.label :ends %> <%= datetime_select("competition", "ends") %></p>
  <p><%= f.label :signup_ends %> <%= datetime_select("competition", "signup_ends") %></p>  
  <p><%= f.label :description %> <%= f.text_area :description %></p>  
  <p><%= f.label :team_stats_config %> <%= f.text_area :team_stats_config %></p>
  <p><%= f.label :challonge_module_url %> <%= f.text_field :challonge_module_url, :size => 100 %></p>
  <p><%= f.label :score_counted %> <%= f.check_box :score_counted %></p>
  <p><%= f.label :kills_counted %> <%= f.check_box :kills_counted %></p>
  <p><%= f.label :deaths_counted %> <%= f.check_box :deaths_counted %></p>
  <p><%= f.label :assists_counted %> <%= f.check_box :assists_counted %></p>
  <p><%= f.label :score_base %> <%= f.select(:score_base, ["score", "kills"]) %></p>
  
  <h4><%= f.label :competition_entries %></h4>
  <%= f.fields_for :competition_entries do |m| %>
    <%= render 'competitions/competition_entry_fields', :f => m %>
  <% end %>
  <p><%= link_to_add_competition_entry_fields "add entry", f %></p><br/>
  
  <h4><%= f.label :competition_judges %></h4>
  <%= f.fields_for :competition_judges do |m| %>
    <%= render 'competitions/competition_judge_fields', :f => m %>
  <% end %>
  <p><%= link_to_add_competition_judge_fields "add judge", f %></p>
  
  <h4><%= f.label :competition_maps %></h4>
  <%= f.fields_for :competition_maps do |m| %>
    <%= render 'competitions/competition_map_fields', :f => m %>
  <% end %>
  <p><%= link_to_add_competition_map_fields "add map", f %></p>
  
  <h4><%= f.label :competition_optional_maps %></h4>
  <%= f.fields_for :competition_optional_maps do |m| %>
    <%= render 'competitions/competition_map_fields', :f => m %>
  <% end %>
  <p><%= link_to_add_competition_optional_map_fields "add opt map", f %></p>
  
  </br>

  <h4><%= f.label :regulations %></h4>
  <p><%= f.text_area :regulations %></p>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Edit competition</h1>

<%= render 'form' %>

app/views/competitions/index.html.erb
<h1><%= t('competitions.page_title') %></h1>

<div id="competition_list">
  <ul>
    <% for competition in @competitions do %>
      <li>
        <p>
          <em>
             <%= link_to competition.long_name, competition %> 
             <span class="dates"><%= time_tag competition.starts, :format => :std %> - <%= time_tag competition.ends, :format => :std %></span> 
             <span class="status"><%= competition.status %></span>
          </em>
          <%= competition.description %>
        </p>
      </li>
    <% end %>
  </ul>
</div>

app/views/competitions/new.html.erb
<h1>New competition</h1>

<%= render 'form' %>

app/views/competitions/show.html.erb
<h1><%= @competition.long_name %></h1>

<% if can? :manage, @competition %>
  <ul class="fancy admin_panel">
    <li><%= link_to "Edit", edit_competition_path(@competition) %></li>  
    <li><%= link_to "Create new", new_competition_path %></li>
  </ul> 
<% end %>

<p><%= @competition.description %> Termin rozgrywek: <%= time_tag @competition.starts %> - <%= time_tag @competition.ends %>.</p>

<% if @subcompetitions.any? %>
<h2>Grupy i rundy</h2>
  <ul class="square">
    <% for sub in @subcompetitions %>
      <li><%= sub.name %> <%= link_to("Edit", edit_competition_path(sub)) if can? :update, @competition %>
    <% end %>
  </ul>
<% end %>

<center>
  <h4>Drużyny</h4>
  <% if @competition.competition_entries.any? %>
    <table id="minimalist-table-hor-a" class="center" summary="<%= t('teams.page_title') %>">
      <thead>
        <tr>
          <th scope="col"><%= t('teams.team') %></th>
          <th scope="col"><%= t('players.roles.captain').capitalize %></th>
          <th scope="col"><%= t('competitions.team_exists_since') %></th>                
        </tr>
      </thead>
      <tbody>
        <% for entry in @competition.competition_entries do %>
          <tr>
            <td><%= link_to name_with_award_image(entry.team, entry.team.full_name), entry.team %></td>
            <td><%= entry.team.owner %></td>
            <td><%= time_ago_in_words(entry.created_at) %></td> 
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  
  <% unless @possible_teams.nil? %>    
    <% for team in @possible_teams %>
      <%= form_tag competition_entries_path, :action => "create" do %>
      <%= hidden_field_tag 'competition_id', @competition.id %>
      <%= hidden_field_tag 'team_id', team.id %>
      <%= submit_tag t('competitions.team_sign_up', :team => team), :confirm => t('are_you_sure'), :class => 'submit button', :name => nil %>    
    <% end %>               
  <% end %>        

  <% end %>
</center>

<% if @competition.challonge_module_url.present? %>
  <h2><%= t('competitions.playoff_tree') %></h2>
  <iframe class="round" src="<%= @competition.challonge_module_url %>" width="930" height="470" frameborder="0" scrolling="auto" allowtransparency="true"></iframe>
<% end %>
  
<h2>Regulamin</h2>  
<%= @competition.regulations.html_safe %>

<% if @competition.competition_maps.any? %>
<h2><%= t('maps.page_title') %></h2>  
<table id="minimalist-table-hor-a" summary="<%= t('maps.page_title') %>">
  <% i = 0 %>
  <% while i < @competition.competition_maps.size do %>
    <tr>          
      <% 3.times do %>        
        <td class="text-center" style="vertical-align: top;">
          <% if i < @competition.competition_maps.size %>
            <% map = @competition.competition_maps[i].map %>
            <div><%= image_tag map.image_url, :alt => map.name %></div>
            <h3><%= map.name %></h3>
          <% end %>
        </td>
      <% i += 1 %>
      <% end %>
    </tr>
  <% end %>
</table>
<% end %>

<% if @competition.competition_optional_maps.any? #FIXME: remove copy-paste %>
<h2><%= t('competitions.optional_maps') %></h2>  
<table id="minimalist-table-hor-a" summary="<%= t('competitions.optional_maps') %>">
  <% i = 0 %>
  <% while i < @competition.competition_optional_maps.size do %>
    <tr>          
      <% 3.times do %>        
        <td class="text-center" style="vertical-align: top;">
          <% if i < @competition.competition_optional_maps.size %>
            <% map = @competition.competition_optional_maps[i].map %>
            <div><%= image_tag map.image_url, :alt => map.name %></div>
            <h3><%= map.name %></h3>
          <% end %>
        </td>
      <% i += 1 %>
      <% end %>
    </tr>
  <% end %>
</table>
<% end %>