config/routes.rb
Unchartedleague::Application.routes.draw do  
  opinio_model

  root :to => 'home#index'  
  devise_for :users  
  match 'matches/:id/check_results' => 'matches#check_results', :via => :get
  match 'matches/:id/commit_results' => 'matches#commit_results', :via => :post
  match 'stats/:competition_id/ranking' => 'stats#ranking', :via => :get, :as => :stats_ranking
  match 'stats/:competition_id/players' => 'stats#players', :via => :get, :as => :stats_players

  resources :teams
  resources :team_participations
  resources :offers
  resources :competitions
  resources :competition_entries
  resources :matches do
    opinio
  end
  resources :match_maps
  resources :maps
  resources :match_map_images
  resources :match_time_proposals
  resources :rounds
  resources :awards
  resources :articles
  resources :users
  

end

app/models/map.rb
class Map < ActiveRecord::Base
  has_many :competition_maps, :dependent => :destroy
  validates :name, :presence => true
  validates :image_url, :presence => true
  
  def to_s
    name
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  load_and_authorize_resource
  
  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @maps }
    end
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
    @map = Map.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @map }
    end
  end

  # GET /maps/new
  # GET /maps/new.json
  def new
    @map = Map.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @map }
    end
  end

  # GET /maps/1/edit
  def edit
    @map = Map.find(params[:id])
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(params[:map])

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render json: @map, status: :created, location: @map }
      else
        format.html { render action: "new" }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.json
  def update
    @map = Map.find(params[:id])

    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map = Map.find(params[:id])
    @map.destroy

    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :ok }
    end
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= semantic_form_for @map do |f| %>
  <%= f.inputs :name, :image_url %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<h1>Listing maps</h1>

<table id="minimalist-table-hor-a">
<% @maps.each do |map| %>
  <tr>
    <td><%= link_to map.name, map %></td>
    <td><%= link_to 'Edit', edit_map_path(map) %></td>
    <td><%= link_to 'Destroy', map, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <td class="text-center" style="vertical-align: top;">
      <div><%= image_tag @map.image_url, :alt => @map.name %></div>
      <h3><%= @map.name %></h3>
    </td>
  </tr>
</table>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>