config/routes.rb
Unchartedleague::Application.routes.draw do  
  opinio_model

  root :to => 'home#index'  
  devise_for :users  
  match 'matches/:id/check_results' => 'matches#check_results', :via => :get
  match 'matches/:id/commit_results' => 'matches#commit_results', :via => :post
  match 'stats/:competition_id/ranking' => 'stats#ranking', :via => :get, :as => :stats_ranking
  match 'stats/:competition_id/players' => 'stats#players', :via => :get, :as => :stats_players

  resources :teams
  resources :team_participations
  resources :offers
  resources :competitions
  resources :competition_entries
  resources :matches do
    opinio
  end
  resources :match_maps
  resources :maps
  resources :match_map_images
  resources :match_time_proposals
  resources :rounds
  resources :awards
  resources :articles
  resources :users
  

end

app/models/award.rb
class Award < ActiveRecord::Base
  default_scope order("importance desc")
  belongs_to :user
  belongs_to :team
  belongs_to :competition
  
  validates :name, :presence => true, :length => { :maximum => 20 }
  validates :icon_url, :presence => true
  validates :inline_icon_url, :presence => true
  validates :importance, :presence => true, :numericality => { :only_integer => true }
  
  def receiver
    unless team.nil?
      team.full_name
    else
      user.psn_name
    end
  end
  
  def full_name
    "#{name} - #{competition.long_name}"
  end
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  load_and_authorize_resource
  
  def index
    @awards = Award.order("created_at desc")
  end
  
  def new
    @award = Award.new
  end
  
  def create
    @award = Award.new(params[:award])
    if @award.save!     
      flash[:success] = "Dodano"      
      redirect_to awards_path
    else
      flash[:error] = "Error"
      redirect_to new_award_path
    end
  end
  
  def edit
    @award = Award.find(params[:id])
  end
  
  def update
    @award = Award.find(params[:id])
    if @award.update_attributes(params[:award])
      flash[:success] = @award.name + " updated"
      redirect_to edit_award_path(@award)
    else
      flash[:error] = "Problem while saving changes"
      render @award
    end
  end
  
  def destroy
    @award = Award.find(params[:id])
      
    if @award.destroy
      flash[:success] = @award.name + " deleted"
      redirect_to awards_path
    else      
      flash[:error] = "Problem while deleting award"
      redirect_to awards_path  
    end
  end
end

app/helpers/awards_helper.rb
module AwardsHelper  
  def name_with_award_image(obj, name = "")
    name = obj if name == ""
    if obj.awards.any?
       return "#{name} <img src='#{obj.awards[0].icon_url}' class='award' title='#{obj.awards[0].full_name}' />".html_safe
    end
    return "#{name}"
  end
end

app/views/awards/_form.html.erb
<% if @award.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@award.errors.count, "error") %> prohibited this competition from being saved:</h2>
    <ul>
    <% @award.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @award do |f| %>
  <p><%= f.label :name %>: <%= f.text_field :name %></p>
  <p><%= f.label :icon_url %>: <%= f.text_field :icon_url %></p>
  <p><%= f.label :inline_icon_url %>: <%= f.text_field :inline_icon_url %></p>
  <p><%= f.label :importance %>: <%= f.text_field :importance %></p>

  <p><%= f.label :competition %> <%= f.select(:competition_id, Competition.all.collect {|x| [x.long_name, x.id]}, { :include_blank => "" } ) %></p>
  <p><%= f.label :user %> <%= f.select(:user_id, User.order("psn_name asc").collect {|x| [x.psn_name, x.id]}, { :include_blank => "" } ) %></p>
  <p><%= f.label :team %> <%= f.select(:team_id, Team.order("name asc").collect {|x| [x.name, x.id]}, { :include_blank => "" } ) %></p>
  
  <%= f.submit %>
<% end %>

app/views/awards/edit.html.erb
<h2>Edit award</h2>

<%= render 'form' %>

app/views/awards/index.html.erb
<h2>Awards</h2>

<ul class="fancy">
  <% for award in @awards %>
  <li>
    <%= award.full_name %> (<%= award.importance %>)</br>
    <%= award.receiver %>
    <%= image_tag award.inline_icon_url, :class => "award" %>
    <br/>
    <div class="admin_panel">
      <%= link_to "Edit", edit_award_path(award) %> 
      <%= link_to "Remove", award_path(award), :method => :delete %>
    </div>
  </li>
  <% end %>
</ul>

app/views/awards/new.html.erb
<h2>Add award</h2>

<%= render 'form' %>