config/routes.rb
Unchartedleague::Application.routes.draw do  
  opinio_model

  root :to => 'home#index'  
  devise_for :users  
  match 'matches/:id/check_results' => 'matches#check_results', :via => :get
  match 'matches/:id/commit_results' => 'matches#commit_results', :via => :post
  match 'stats/:competition_id/ranking' => 'stats#ranking', :via => :get, :as => :stats_ranking
  match 'stats/:competition_id/players' => 'stats#players', :via => :get, :as => :stats_players

  resources :teams
  resources :team_participations
  resources :offers
  resources :competitions
  resources :competition_entries
  resources :matches do
    opinio
  end
  resources :match_maps
  resources :maps
  resources :match_map_images
  resources :match_time_proposals
  resources :rounds
  resources :awards
  resources :articles
  resources :users
  

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :competition
  belongs_to :team1, :class_name => "Team"
  belongs_to :team2, :class_name => "Team"
  belongs_to :judge, :class_name => "User"
  belongs_to :forfeiting_team, :class_name => "Team"
  belongs_to :round
  has_many :match_maps, :dependent => :destroy, :autosave => true
  has_many :maps, :through => :match_maps
  has_many :match_entries
  has_many :match_time_proposals, :dependent => :destroy
  
  opinio_subjectum

  validates_associated :match_maps
  
  def open_spot?
    team2.nil?
  end
  
  def not_played?
    !not_played_comment.nil? and not_played_comment != ""
  end
  
  def generate_match_maps    
    map_ids = competition.competition_maps.collect { |x| x.map_id }.sort_by { rand }.slice(0...3)
    for map_id in map_ids
      match_maps.build(:map_id => map_id)
    end
  end
  
  def teams
    [team1, team2]
  end

  def has_valid_scores?
    return (processed and forfeiting_team.nil? and not not_played?)
  end
  
  def result
    unless not_played?
      if processed
        team1wins = 0
        team2wins = 0      
        if forfeiting_team.nil?
          for match_map in match_maps
            if match_map.winning_team == team1
              team1wins += 1
            elsif match_map.winning_team == team2
              team2wins += 1
            end
          end
        else
          if forfeiting_team == team1
            team2wins = 2
          elsif forfeiting_team == team2
            team1wins = 2
          end
        end
        team1wins.to_s + ":" + team2wins.to_s      
      else
        "-:-"
      end
    else
      "brak"
    end
  end

  def maps_won_by_team (team)
    wins = 0
    if forfeiting_team.nil?
      for match_map in match_maps
        if match_map.winning_team == team
          wins += 1
        end
      end    
    else
      if forfeiting_team != team
        wins = 2
      end
    end
    return wins
  end
  
  def winning_team
    if maps_won_by_team(team1) > maps_won_by_team(team2)
      team1
    else
      team2
    end
  end

  def team_score_on_map (team, map)
    if forfeiting_team.nil?
      for match_map in match_maps
        if match_map.map == map
          if team == team1
            return match_map.team1score
          elsif team == team2
            return match_map.team2score
          end
        end
      end
    else
      if forfeiting_team == team
        0
      else
        25
      end
    end
    "-"
  end
  
  def detailed_result(user = nil) # FIXME: combine with result method
    if not_played?
      "brak"
    elsif forfeiting_team.nil?
      if processed or user == judge
        team1wins = 0
        team2wins = 0
        scores = []
        for match_map in match_maps
          if match_map.match_entries.any?
            if match_map.winning_team == team1
              team1wins += 1
            elsif match_map.winning_team == team2
              team2wins += 1
            end
            scores << match_map.team1score.to_s + "-" + match_map.team2score.to_s
          end
        end
        team1wins.to_s + ":" + team2wins.to_s + " (" + scores.join(', ') + ")"
      else
        result
      end
    else
      if forfeiting_team == team1
        "0:2 (0:25, 0:25)"
      else
        "2:0 (25:0, 25:0)"
      end
    end
  end
  
  def can_be_edited_by? (user) # FIXME: merge with @edit_mode in the controller
    ((!processed and judge == user) or (!processed and !locked_by_judge and (team1.has_member? user or team2.has_member? user)))
  end
  
  def self.user_matches(user)
    ids = Team.user_teams(user).collect { |x| x.id }
    Match.where('team1_id in (?) or team2_id in (?)', ids, ids)        
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
  
  def index_current_NOTUSED
    active_competitions = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11] # FIXME
    
    if not current_user.nil? and params[:show_my].present? and params[:show_my] == 'true'
      @matches = Match.filtered(current_user).where("competition_id in (?)", active_competitions).order("scheduled_at desc").paginate(:per_page => 20, :page => params[:page])    
    elsif not current_user.nil? and params[:show_judged].present? and params[:show_judged] == 'true'
      @matches = Match.where("judge_id = ? and competition_id in (?)", current_user.id, active_competitions).order("scheduled_at desc").paginate(:per_page => 20, :page => params[:page])        
    else
      @rounds = Round.where("competition_id in (?)", active_competitions).order("number desc, competition_id asc")
    end
  end
  
  def index 
    @competition = Competition.find(23) # FIXME (also hardcoded in query in show!!!!
    active_competitions = @competition.all_competitions
    if user_signed_in? and params[:show_my].present? and params[:show_my] == 'true'
      @matches = Match.user_matches(current_user).where("competition_id in (?)", active_competitions).order("scheduled_at asc") # pagination?
    elsif user_signed_in? and params[:show_judged].present? and params[:show_judged] == 'true'
      @matches = Match.where("judge_id = ? and competition_id in (?)", current_user.id, active_competitions).order("scheduled_at asc")    
    else
      @matches = Match.where('competition_id in (?) and round_id is ?', active_competitions, nil).order("scheduled_at asc")
      @rounds = Round.where("competition_id in (?)", active_competitions).order("number desc, competition_id asc")
    end
    
    if user_signed_in?
      teams = Team.joins(:competitions, :team_participations).where("user_id = ? and role = ? and competitions.id = ?", current_user.id, 0, @competition.id)
      @managed_team = nil
     
      for t in teams
        if @competition.teams.include? t
          @managed_team = t
          @match = Match.new
          @match.team1 = @managed_team
          @match.competition = @competition
          break
        end
      end      
    end
  end
  
  def show    
    @match = Match.find(params[:id])

    if @match.scheduled_at.nil? 
      if user_signed_in?
        teams = Team.joins(:competitions, :team_participations).where("user_id = ? and role = ? and competitions.id = ? and (teams.id = ? or teams.id = ?)", current_user.id, 0, 23, @match.team1.id, @match.team2.id) # FIXME: hardcoded competition!!!!
        if teams.empty?
          @managed_team = nil
        else
          @managed_team = teams[0]          
        end
     end
    end
    
    @edit_mode = false    
    if user_signed_in? and @match.scheduled_at.present? and !@match.processed      
      @edit_mode = (current_user == @match.judge)
      if !@edit_mode
        @edit_mode = !@match.locked_by_judge
        @edit_mode &= (@match.team1.has_member? current_user or @match.team2.has_member? current_user)
      end
    end
    
    if @edit_mode
      for match_map in @match.match_maps do # FIXME: merge with MatchMapsController
        for team in @match.teams        
          max = team.all_users.size
          max = @match.competition.max_players_per_team if max > @match.competition.max_players_per_team
          existing = match_map.match_entries.select { |x| x.team == team }.collect { |x| x.user.id }
          team.all_users.select { |x| not existing.include? x.id }.slice(0...(max - existing.size)).each do |x| 
            match_map.match_entries.build(:team_id => team.id, :match_id => @match.id, :user_id => x.id)
          end
        end
      end    
    end
  end
  
  def create    
    @match = Match.new(params[:match])
    if Time.now > @match.competition.ends or @match.scheduled_at > @match.competition.ends or @match.scheduled_at < @match.competition.starts
      flash[:error] = t('matches.match_should_be_scheduled_within_competition_time')
      redirect_to matches_path
    else
      @match.processed = false
      @match.locked_by_judge = false
      if @match.save
        flash[:success] = t('matches.proposal_created_successfully_without_opponent')
        redirect_to matches_path
      else       
        render :action => 'index'
      end    
    end
  end
  
  def update 
    @match = Match.find(params[:id])    
    if params[:team2_id].present? # merge with MatchTimeProposal?
      @team2 = Team.find(params[:team2_id])
      if @match.open_spot? and @team2.can_be_managed_by? current_user
        @match.team2 = @team2
        @match.judge = @match.competition.get_judge
        @match.generate_match_maps
        if @match.save
          UserMailer.match_time_accepted(@match).deliver
          flash[:success] = t('matches.proposal_accepted_successfully')
          redirect_to match_path @match
        else      
          flash[:error] = t('matches.cannot_accept_with_error') 
          redirect_to matches_path  
        end
      else
        flash[:error] = t('matches.cannot_accept')
        redirect_to matches_path
      end
    else # normal update by judge or admin
      if current_user == @match.judge or can? :manage, @match
        if params[:match].present?
          if @match.update_attributes(params[:match])
            flash[:success] = "Mecz zaktualizowany"            
          else
            flash[:error] = "Problem podczas zapisu. Prosimy o kontakt z administratorem."
          end          
        elsif params[:remove_all_results]
          for entry in @match.match_entries
            entry.destroy
          end
          flash[:success] = "Wyniki wyczyszczone."     
        end
        redirect_to match_path(@match)
      end
    end
  end
  
  def destroy
    begin
      @match = Match.find(params[:id])
      if @match.open_spot? and (can?(:destroy, @match) or @match.team1.can_be_managed_by? current_user)
        if @match.destroy
          flash[:success] = t('matches.proposal_removed_successfully')
          redirect_to matches_path
        else      
          flash[:error] = t('matches.cannot_remove_with_error')
          redirect_to matches_path  
        end
      else
        flash[:error] = t('matches.cannot_remove')
        redirect_to matches_path
      end
    rescue Exception
      flash[:error] = t('matches.cannot_remove_with_error')
      redirect_to matches_path
    end
  end
  
  def check_results    
    @match = Match.find(params[:id])
    @match.locked_by_judge = true
    @match.save!   
    
    # TODO, move this section to somewhere else
    @competition_players = {}
    @competition_players[@match.team1] = Set.new
    @competition_players[@match.team2] = Set.new
    for team in @match.teams do      
      for match in Match.where('(team1_id = ? or team2_id = ?) and competition_id = ?', team.id, team.id, @match.competition_id) do #FIXME (nearly the same as teams_controller        
        for entry in match.match_entries          
          if entry.team == team            
            @competition_players[team].add entry.user
          end
        end
      end
    end    
  end
  
  def commit_results    
    match = Match.find(params[:id])
    if current_user == match.judge
      match.processed = true
      if match.save
        flash[:success] = t('matches.results_commited_successfully')
        redirect_to match
      else
        flash[:success] = t('matches.results_commit_error')
        redirect_to matches_path
      end
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
  def match_teams(match)
    link_to(name_with_award_image(match.team1), match.team1) + " vs " + (match.open_spot? ? t('matches.open_spot') : (link_to name_with_award_image(match.team2), match.team2))
  end
  
  def match_teams_without_awards(match)
    link_to(match.team1.to_s, match.team1) + " vs " + (match.open_spot? ? t('matches.open_spot') : (link_to match.team2.to_s, match.team2))
  end
  
  def match_teams_plain(match)
    match.team1.to_s + " vs " + (match.open_spot? ? t('matches.open_spot') : match.team2.to_s)
  end
end

app/views/matches/_match_entries.html.erb
<center><%= match_map.team_in_game team %></center>
<table>
  <thead>
    <th scope="col"><%= t('players.player').capitalize %></th>
    <% if match_map.match.competition.score_counted? %>
      <th scope="col"><%= t('matches.score').capitalize %></th>
    <% end %>
    <% if match_map.match.competition.kills_counted? %>
      <th scope="col"><%= t('matches.kills').capitalize %></th>
    <% end %>
    <% if match_map.match.competition.deaths_counted? %>
      <th scope="col"><%= t('matches.deaths').capitalize %></th>
    <% end %>
    <% if match_map.match.competition.assists_counted? %>
      <th scope="col"><%= t('matches.assists').capitalize %></th>
    <% end %>
  </thead>  
  <% for match_entry in match_map.match_entries %>
    <% if match_entry.team == team %>      
      <tr>          
        <td><%= name_with_award_image(match_entry.user) %></td>        
        <% if match_map.match.competition.score_counted? %>
          <td><%= match_entry.score %></td>
        <% end %>
        <% if match_map.match.competition.kills_counted? %>
          <td><%= match_entry.kills %></td>
        <% end %>
        <% if match_map.match.competition.deaths_counted? %>
          <td><%= match_entry.deaths %></td>
        <% end %>
        <% if match_map.match.competition.assists_counted? %>
          <td><%= match_entry.assists %></td>
        <% end %>
      </tr>
    <% end %>
  <% end %>  
</table>

app/views/matches/_match_entry.html.erb
<table>  
  <thead>
    <th scope="col">Zawodnik</th>
    <th scope="col">Fragi</th>
    <th scope="col">Śmierci</th>
    <th scope="col">Asysty</th>
  </thead>
  <%= form_for match_map do |f| %>
    <%= f.fields_for :match_entries do |me| %>
      <% if me.object.team == team %>
        <tr>      
          <td><%= me.object.user %></td>
          <td><%= me.text_field :kills, :size => 1 %></td>
          <td><%= me.text_field :deaths, :size => 1 %></td>  
          <td><%= me.text_field :assists, :size => 1 %></td> 
        </tr>
      <% end %>
    <% end %>
  <% end %>
</table>

app/views/matches/_match_map_picture.html.erb
<% unless match_map.match_map_image.nil? %>
  <table style="margin-left: auto; margin-right: auto;">
    <thead>
      <th colspan="2" scope="col"><%= t('matches.match_photo') %></th>      
    </thead>  
    <tbody>
      <tr>
        <td class="text-center" id="showimage_<%= match_map.id %>">
          <%= link_to (image_tag match_map.match_map_image.url, :alt => match_teams_plain(match_map.match), :width => 500), match_map.match_map_image.url %>
        </td>
      </tr>    
    </tbody>
  </table>
<% end %>

app/views/matches/_match_map_picture_edit.html.erb
<table style="margin-left: auto; margin-right: auto;">
  <thead>
    <th colspan="2" scope="col"><%= t('matches.match_photo') %></th>      
  </thead>  
  <tbody>
    <tr>
      <td class="text-center">
        <% current_user.reset_authentication_token! if current_user.authentication_token.nil? %>
        <script type="text/javascript" charset="utf-8">                  
           $(document).ready(function() {
             $('#upload_picture_<%= match_map.id %>').uploadify({
               'uploader' : '<%= asset_path 'uploadify.swf' %>',
               'buttonText' : '<%= t('matches.add_screen') %>',
               'completedText' : '<%= t('matches.add_screen_completed') %>',
               'script' : '<%= match_map_images_path %>',
               'cancelImg' : '<%= asset_path 'cancel.png' %>',
               'sizeLimit' : <%= 1.megabyte %>,
               'fileExt'   : '*.png;*.jpg;*.gif',
               'auto' : true,              
               'multi' : false,
               'removeCompleted': false,
               'scriptData': {
                'auth_token': '<%= current_user.authentication_token %>',
                'match_map[id]': '<%= match_map.id %>'
               },
               'onSelect': function (event, queueID, fileObj, response, data) {
                 $("#showimage_<%= match_map.id %>").empty();
               },
               'onComplete': function (event, queueID, fileObj, response, data) {
                 $("#showimage_<%= match_map.id %>").html('<a href="' + response + '" target="_blank"><img src="' + response + '?' + (new Date().getTime()) + '" width="500" /></a>');
               }
             });
           });
        </script>
        <%= file_field_tag :picture, :id => "upload_picture_#{match_map.id}" %> 
      </td>
    </tr>
    <tr>
      <td class="text-center" id="showimage_<%= match_map.id %>">
        <% unless match_map.match_map_image.nil? %>
          <%= link_to (image_tag match_map.match_map_image.url, :alt => match_teams_plain(match_map.match), :width => 500), match_map.match_map_image.url %>
        <% end %>
      </td>
    </tr>    
  </tbody>
</table>

app/views/matches/_matches.html.erb
<table id="minimalist-table-hor-a" summary="<%= t('matches.page_title') %>">
  <thead>
    <tr>
      <th scope="col"><%= t('matches.match') %></th>
      <th scope="col"><%= t('matches.result') %></th>
      <th scope="col"><%= t('matches.scheduled_at') %></th>
      <th scope="col"><%= t('competitions.page_title') %></th>
      <th scope="col"><%= t('more') %></th>         
    </tr>
  </thead>
  <tbody>      
    <% for match in matches do %>  
      <tr>
        <td><%= match_teams(match) %></td>
        <td>
          <%= match.result %> 
          <% if can? :destroy, match and match.open_spot? %>
            <span class="admin_panel"><%= link_to 'De', match_path(match), :confirm => 'Pewny?', :method => :delete %></span>
          <% end %>
        </td>
        <td><%= (!match.scheduled_at.nil? ? time_tag(match.scheduled_at) : pluralize_localized(match.match_time_proposals.size, "propozycja")) %></td>    
        <td><%= link_to match.competition.name, competition_path(match.competition.root) %></td>               
        <td>
          <% if not managed_team.nil? and match.open_spot? %>
            <% if match.team1 != managed_team %>
              <%= form_tag match_path(match), :method => :put do %>                
                <%= hidden_field_tag 'team2_id', managed_team.id %>                
                <%= submit_tag t('matches.accept'), :confirm => t('are_you_sure'), :class => 'submit button', :name => nil %>    
              <% end %>            
            <% else %>
              <%= form_tag match_path(match), :method => :delete do %>                    
                <%= submit_tag t('matches.remove_proposal'), :confirm => t('are_you_sure'), :class => 'submit button', :name => nil %>    
              <% end %>            
            <% end %>
          <% elsif not match.open_spot? %>
            <%= form_tag match_path(match), :method => :get do %>                    
              <%= submit_tag t('matches.more'), :class => 'submit button', :name => nil %>    
            <% end %>  
          <% else %>            
            <%= t('none') %>
          <% end %>          
        </td>     
      </tr>
    <% end %>
  </tbody>
</table>

app/views/matches/_results_summary.html.erb
<h3><%= t('matches.result') + ": " + @match.detailed_result(current_user) %></h3>
<p>Liczba graczy aktywnych po tym meczu:
  <ul>
    <% @match.teams.each do |team| %>
      <% players = @competition_players[team] %>
      <li style="text-decoration: underline; cursor: pointer" onClick="alert('<%= players.to_a.join(', ') %>')"><%= team.name %> = <%= players.size %></li>    
    <% end %>
  </ul>
</p>
<%= form_tag "/matches/#{match.id}/commit_results", :method => :post do %>
  <%= submit_tag t('matches.commit_match_results'), :confirm => t('matches.commit_are_you_sure'), :class => "submit btn-form-single", :name => nil %>
<% end %>

app/views/matches/check_results.js.erb
$('#results_summary').html("<%= escape_javascript(render('matches/results_summary', {:match => @match, :competition_players => @competition_players})) %>");

app/views/matches/show.html.erb
<h1><%= match_teams_without_awards(@match) %></h1>

<% if @match.processed %>
  <h2><%= t('matches.result') %>: <%= @match.detailed_result %></h2>
<% end %>
<% if @match.judge.nil? %>
  <%= info_section t('matches.waiting_to_be_accepted') %>
<% elsif @match.scheduled_at.nil? %>
  <% if @managed_team.nil? %>
    <% if @match.judge == current_user %>
      <%= info_section t('matches.waiting_to_be_scheduled_judge') %>
    <% else %>
      <%= info_section t('matches.waiting_to_be_scheduled') %>  
    <% end %>
  <% else %>
    <%= info_section t('matches.waiting_to_be_scheduled_captain') %>
  <% end %>
<% elsif @edit_mode %>
  <% if @match.judge == current_user %>
    <%= info_section t('matches.edit_mode_intro_for_judge') %>
  <% else %>
    <%= info_section t('matches.edit_mode_intro') %>
  <% end %>
<% end %>
<ul class="fancy">  
  <li><%= t('competitions.page_title') %>: <%= @match.competition %></li>
  <li><%= t('matches.scheduled_at') %>: <%= (!@match.scheduled_at.nil? ? time_tag(@match.scheduled_at) : "?") %></li>
  <li><%= t('matches.judge') %>: <%= (@match.judge.nil? ? t('matches.no_judge') : @match.judge) %></li>  
  <li><%= t('matches.processed') %>: <%= (@match.processed ? t('choice_yes'): t('choice_no')) %></li>
  <% unless @match.forfeiting_team.nil? %>
    <li><%= "#{t('matches.forfeited_by')} #{@match.forfeiting_team.name}" %></li>
  <% end %>
  <% if @match.not_played? %>
    <li>Mecz nierozegrany. <%= @match.not_played_comment %></li>
  <% end %>
</ul>

<% if current_user == @match.judge or can? :manage, @match %>
  <div class="admin_panel">
    <h4>Panel sędziowski</h4>
    <%= form_for @match do |f| %>
      <% if can? :manage, @match %>
        <p><%= f.label :judge %> <%= f.select(:judge_id, @match.competition.competition_judges.collect {|x| [x.user, x.user.id]}) %> (admin only)</p>
      <% end %>
      <p><%= f.label :not_played_comment %> <%= f.text_field :not_played_comment %></p>
      <p><%= f.label :forfeiting_team %> <%= f.select(:forfeiting_team_id, @match.teams.collect {|x| [x.name, x.id]}, { :include_blank => "" } ) %></p>      
      <p><%= f.check_box :processed %> <%= f.label :processed %> (musi być zakończony, aby wyniki się wliczały)</p>      
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
    <% if can? :manage, @match %>
      <p style="padding-top: 5px;"><%= link_to "Remove all match entries (#{@match.match_entries.size})", match_path(@match, :remove_all_results => true), :method => :put, :confirm => "Pewny?" %> (admin only)</p>
      <p style="padding-top: 5px;"><%= link_to "Remove match", match_path(@match), :method => :delete, :confirm => "Pewny?" %> (admin , not available yet)</p>
  <% end %>
  </div><br/>
<% end %>
  
<% if @match.scheduled_at.nil? %>  
  <% if !@managed_team.nil? or current_user == @match.judge %>  
    <% if @match.match_time_proposals.any? %>
      <table id="minimalist-table-hor-a" summary="<%= t('matches.page_title') %>">
        <thead>
          <tr>
            <th scope="col"><%= t('matches.scheduled_at') %></th>
            <th scope="col"><%= t('matches.proposed_by') %></th>
            <th scope="col"><%= t('more') %></th>         
          </tr>
        </thead>
        <tbody>
          <% for p in @match.match_time_proposals do %>
            <tr>             
              <td style="vertical-align: middle;"><%= time_tag(p.proposal) %></td>
              <td style="vertical-align: middle;"><%= p.team %></td>
              <td>               
                <% if !@managed_team.nil? and p.team != @managed_team %>
                  <%= form_tag match_time_proposal_path(p), :method => :put do %>                    
                    <%= submit_tag t('matches.accept'), :confirm => t('are_you_sure'), :class => 'submit button', :name => nil %>    
                  <% end %>            
                <% elsif p.team == @managed_team %>
                  <%= form_tag match_time_proposal_path(p), :method => :delete do %>                    
                    <%= submit_tag t('matches.remove_proposal'), :confirm => t('are_you_sure'), :class => 'submit button', :name => nil %>    
                  <% end %>            
                <% else %>                
                  <%= t('none') %>
                <% end %>                
              </td>     
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <%= t('matches.no_date_proposals') %>
    <% end %>
    
    <% unless @managed_team.nil? %>
      <div id="stylized-form">
        <%= form_tag :controller => :match_time_proposals, :action => 'create' do %>
          <%= hidden_field_tag "match_time_proposal[match_id]", @match.id %>
          <%= hidden_field_tag "match_time_proposal[team_id]", @managed_team.id %>      
          <div class="wrapper-block">
            <label><%= t('activerecord.attributes.match.scheduled_at') %>:<span class="small-label"><%= t('matches.propose_your_time') %></span></label>
            <%= datetime_select("match_time_proposal", "proposal", :start_year => Date.current.year - 1, :end_year => Date.current.year + 1) %>
          </div>    
          <input type="submit" value="<%= t('matches.propose') %>" class="submit btn-form" />
        <% end %>
      </div>
    <% end %>
  <% end %>
<% elsif @match.forfeiting_team.nil? and not @match.not_played? %>  
  <% edit = @edit_mode ? "_edit" : "" %>
  <table id="minimalist-table-hor-a" summary="<%= t('matches.page_title') %>">
    <thead>
      <% if @edit_mode or @match.processed %>
        <tr>
          <th scope="col" class="text-center" style="vertical-align: top;"><%= t('matches.maps') %></th>
          <th scope="col" class="text-center"><%= @match.team1 %></th>
          <th scope="col" class="text-center"><%= @match.team2 %></th>
        </tr>
      <% else %>
        <tr>
          <th scope="col" class="text-center"><%= t('matches.map') %> #1</th>
          <th scope="col" class="text-center"><%= t('matches.map') %> #2</th>
          <th scope="col" class="text-center"><%= t('matches.map') %> #3</th>
        </tr>
      <% end %>
    </thead>
    <tbody>
      <% if @edit_mode or @match.processed %>
        <% for match_map in @match.match_maps %>
          <% if @edit_mode or match_map.match_entries.any? %>
            <tr>
              <td class="text-center" rowspan="2" style="vertical-align: top;">                
                <div><%= image_tag match_map.map.image_url, :alt => match_map.map.name %></div>
                <h3><%= match_map.map.name %></h3>
              </td>
              <td class="text-center">
                <div id="match_entries_<%= match_map.id %>_<%= @match.team1.id %>">
                  <%= render 'match_entries' + edit, :match_map => match_map, :team => @match.team1 %>   
                </div>
              </td>
              <td class="text-center">
                <div id="match_entries_<%= match_map.id %>_<%= @match.team2.id %>">
                  <%= render 'match_entries' + edit, :match_map => match_map, :team => @match.team2 %>
                </div
              </td>
            </tr>
            <tr style="border-bottom: 1px dotted #6678B1;">        
              <td class="text-center" colspan="2">
                <%= render 'match_map_picture' + edit, :match_map => match_map %>
              </td>
            </tr>
          <% end %>
        <% end %>
      <% else %>
        <tr>          
          <% for i in 0...3 # FIXME %>        
            <% match_map = @match.match_maps[i] %>
            <td class="text-center" style="vertical-align: top;">
              <div><%= image_tag match_map.map.image_url, :alt => match_map.map.name %></div>
              <h3><%= match_map.map.name %></h3>
            </td>
          <% end %>
        </tr>
      <% end %>
      <% if @edit_mode and current_user == @match.judge %>
        <tr>
          <td colspan="3" class="text-center">
            <%= form_tag "/matches/#{@match.id}/check_results", :method => :get, :remote => true do %>
              <%= submit_tag t('matches.check_and_commit_match'), :class => "submit btn-form-single", :name => nil, :onClick => "window.show_waiting_info('#results_summary');" %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td colspan="3" class="text-center" id="results_summary">          
          </td>
        </tr>    
      <% end %>
    </tbody>  
  </table>
<% end %>

<%=
    comments_for @match, :page => params[:page]
%>